### ISSUE TITLE
opera broke after fontconfig was upgraded from 2.12 to 2.13

### ISSUE THREAD

**Issue by crocket** [voidlinux/void-packages#14161]
### System

* xuname: Void 4.9.93_1 x86_64 AuthenticAMD uptodate rrrmF
* package: opera-52.0.2871.99_1

### Expected behavior

Opera should launch

### Actual behavior

Opera spits out fontconfig erros and doesn't launch its window.

### Steps to reproduce the behavior

```
xbps-install -Su
opera
```

**Comment by cr6git** [comment]
I'm not saying that is the problem, but... I found the commit where `freetype-devel` was added to the template:

[3c943698825788adca4efb67d911c29d43122ef7](https://github.com/voidlinux/void-packages/commit/3c943698825788adca4efb67d911c29d43122ef7)

Simple question: I wonder if this is still needed? what do you think @pullmoll , @diogoleal ?
Regards.

**Comment by newbluemoon** [comment]
Opera is working for me. Does it work when you start it like

    LANG=C opera

?

Then it’s the same problem which #13773 is supposed to fix.

**Comment by maxice8** [comment]
> Perhaps, it's time for void linux maintainers to consider adopting gentoo's way of keeping binary packages stable. Binary packages will break often on void linux without some sort of stability guarantee.

What is gentoo's way ?

**Comment by cr6git** [comment]
I can see the long output relative of fontconfig:
````
$ opera
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
[...]
````
But after that Opera starts & works.

**Comment by cr6git** [comment]
I don't know what commit [3c943698825788adca4efb67d911c29d43122ef7](https://github.com/voidlinux/void-packages/commit/3c943698825788adca4efb67d911c29d43122ef7) was supposed to fix.
On my machine I recompiled Opera, but without `hostmakedepends="freetype-devel"` and without the symlink `ln -sf /usr/lib/libfreetype.so.6 ...` and it works fine. To be honest I can't see the difference...

**Comment by newbluemoon** [comment]
@cr6git The reason is #5494.

**Comment by pullmoll** [comment]
Since cr6git verified that opera works without the hack we obviously can remove it again.

**Comment by pullmoll** [comment]
I merged #13773 perhaps this helps? I'll take care of opera, though, perhaps tomorrow... if nobody beats me to it.

**Comment by crocket** [comment]
After installing `fontconfig-2.13.0_2`, I still see the same errors.

[opera.log](https://github.com/voidlinux/void-packages/files/1978249/opera.log)

**Comment by pullmoll** [comment]
So then let's build opera without the hack.

**Comment by maxice8** [comment]
@crocket not happy about the extra work of maintaning multiple versions of a package, even less because some propietary software can't handle free software.

**Comment by crocket** [comment]
Without changes to xbps, binary packages will keep breaking often.

**Comment by newbluemoon** [comment]
@crocket Do you have dbus running?

**Comment by crocket** [comment]
```
dejavu-fonts-ttf-2.37_1
font-adobe-100dpi-1.0.3_4
font-adobe-75dpi-1.0.3_4
font-adobe-utopia-100dpi-1.0.4_4
font-adobe-utopia-75dpi-1.0.4_4
font-adobe-utopia-type1-1.0.4_4
font-alias-1.0.3_3
font-bh-100dpi-1.0.3_4
font-bh-75dpi-1.0.3_4
font-bh-lucidatypewriter-100dpi-1.0.3_4
font-bh-lucidatypewriter-75dpi-1.0.3_4
font-bh-ttf-1.0.3_4
font-bh-type1-1.0.3_4
font-bitstream-100dpi-1.0.3_4
font-bitstream-75dpi-1.0.3_4
font-bitstream-type1-1.0.3_4
font-cursor-misc-1.0.3_4
font-daewoo-misc-1.0.3_4
font-dec-misc-1.0.3_4
font-ibm-type1-1.0.3_4
font-isas-misc-1.0.3_4
font-jis-misc-1.0.3_3
font-misc-misc-1.1.2_5
font-mutt-misc-1.0.3_4
font-util-1.3.1_2
gsfonts-8.11_4
liberation-fonts-ttf-2.00.1_1
noto-fonts-cjk-20150616_1
xorg-fonts-7.6_4
```

**Comment by cr6git** [comment]
@crocket it is one of these fonts that is causing the issue.

**Comment by crocket** [comment]
How do you know?

**Comment by cr6git** [comment]
I did a test: installed `xorg-fonts` --> fonts broken in `firefox-esr`.

**Comment by crocket** [comment]
But, xorg-fonts is required by `xorg`.

**Comment by newbluemoon** [comment]
When I do a gdb backtrace I get

```
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff7bc2e65 in __GI___pthread_mutex_lock (mutex=0x71fff60) at ../nptl/pthread_mutex_lock.c:80
#2  0x0000000003651df8 in ?? ()
#3  0x000000000470a0b5 in ?? ()
#4  0x000000000470993a in ?? ()
#5  0x000000000286b4db in ?? ()
...
```

This seems to be some sort of deadlock but no clue if fontconfig is the cause or something entirely else.

**Comment by cr6git** [comment]
@crocket the package [xorg](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/xorg/template) is just a meta-package, you don't really need it to start your X session. The same for [xorg-fonts](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/xorg-fonts/template), you can drop it and just keep the fonts you want...

**Comment by crocket** [comment]
Does installing xorg-fonts result in this issue?

**Comment by Oreo639** [comment]
I thought this was a known issue. 
Here is a solution I can say works. http://blog.brunomiguel.net/geekices/how-to-get-good-font-rendering-in-void-linux/

Installing font-adobe-75dpi caused the issue for me.

**Comment by Oreo639** [comment]
~~im a retard~~
