### ISSUE TITLE
Firefox 54 on x86_64-musl 

### ISSUE THREAD

**Issue by emacsomancer** [voidlinux/void-packages#6746]
After the latest update to FF 54, on musl, FF is not working. It works fine initially, but after restarting the first time (and any subsequent time) every tab crashes and prompts for reload (which it won't). Removing the ~/.mozilla directory temporarily resolves, but again any restart puts it back into the non-working state.

**Comment by loreb** [comment]
Same issue here, on my laptop and on a qemu vm.
Fwiw I'm temporarily working around it by using firefox-esr instead.
If you can think of any info I can provide to help figuring out what's going on let me know.

**Comment by emacsomancer** [comment]
On my pure Void musl laptop, I've done the same (firefox-esr). On my Bedrock latop with Void musl as the main stratum, I've just used FF (& Chromium as well actually, since it's also become a bit funny on musl) from Void glibc.

None of these are an actual solution though.

**Comment by loreb** [comment]
I think I found the problem - with firefox (not firefox-esr) try disabling electrolysis -- https://wiki.mozilla.org/Electrolysis#Firefox_Release

Works for me(tm).


[OT] thanks for mentioning Bedrock, it looks VERY interesting!

**Comment by chmod77** [comment]
The problem still persist on 55.0.1

**Comment by Duncaen** [comment]
Fixed in 61b94dfa43d1b1a267edff7cfa2c8049f7ad0599.

**Comment by emacsomancer** [comment]
Still occurs on some sites. usps.com for instance still has this issue on musl firefox.  the glibc firefox (with the same config, on the same machine) does not.

**Comment by Duncaen** [comment]
Can't reproduce and its definitvely a completely unrelated issue to the fixed one.

**Comment by emacsomancer** [comment]
That may be, but it is still the same symptoms.
