### ISSUE TITLE
cinnamon-settings doesn't link to PAM correctly (python: undefined symbol: pam_start)

### ISSUE THREAD

**Issue by Antonio-Malcolm** [voidlinux/void-packages#914]
Getting this issue when trying to start cinnamon-settings:
"python: undefined symbol: pam_start"
Cinnamon applets won't launch from the menu, either.

**Comment by xtraeme** [comment]
This should be fixed with cinnamon-2.4, which I've just pushed to the master branch.

Wait until all cinnamon packages are built, upgrade your system and try again.

Let me know if you can reproduce it... because I wasn't able to reproduce it with 2.4.x.

**Comment by xtraeme** [comment]
Fixed with the 2.4.x update, thanks.

**Comment by Antonio-Malcolm** [comment]
Just updated, and am still seeing the issue.
Updated with xbps-intsall -Syu, and saw the update to 2.4.x
Also tried uninstalling and reinstalling the package, and am seeing the same error.
Additionally, I'm seeing a warning "Couldn't register with accessibility bus:..."
I have D-Bus up and running, with the appropriate entry in /var/service

**Comment by xtraeme** [comment]
I cannot reproduce it. Try `xbps-query -s cinnamon`.

**Comment by Antonio-Malcolm** [comment]
From that, I get:
cinnamon-2.4.6_1
cinnamon-control-center-2.4.2_2
cinnamon-desktop-2.4.2_1
cinnamon-menus-2.4.1_1
cinnamon-screensaver-2.4.0_1
cinnamon-session-2.4.3_1
cinnamon-settings-daemon-2.4.3_1
cinnamon-translations-2.4.1_1
cjs-2.4.1_1
libcinnamon-control-center-2.4.2_2
libnemo-2.4.5_1
muffin-2.4.3_1
nemo-2.4.5_1

**Comment by xtraeme** [comment]
Paste the errors exactly after executing "cinnamon-settings".

**Comment by Antonio-Malcolm** [comment]
(process:1403): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

** (cinnamon-settings.py:1403): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
python: undefined symbol: pam_start

**Comment by xtraeme** [comment]
Try `xbps-pkgdb -a 2>err` and paste `err`.

**Comment by Antonio-Malcolm** [comment]
failed to lock pkgdb: Permission denied

**Comment by xtraeme** [comment]
You need to be root.

**Comment by Antonio-Malcolm** [comment]
D'oh! Taht's right! Yeah, lemme' try that again...

WARNING: base-files: modified symlink /etc/mtab points to /proc/self/mounts (shall be /proc/1459/mounts)
ERROR: base-files: broken symlink /usr/lib/ld-linux.so.2 (target: ../lib32/ld-linux.so.2)
ERROR: cinnamon: broken symlink /etc/xdg/menus/cinnamon-applications-merged (target: /etc/xdg/menus/applications-merged)

**Comment by xtraeme** [comment]
`xbps-query -l|wgetpaste`

**Comment by Antonio-Malcolm** [comment]
Apparently nothing was received. Perhaps the connection failed. Enable --verbose or
--debug to get the output from wget that can help diagnose it correctly.

...with --verbose

Apparently nothing was received. Perhaps the connection failed.
http://: Invalid host name.
--2015-01-24 04:08:56--  http://bpaste.net/
Resolving bpaste.net (bpaste.net)... 84.22.98.66, 2a02:2770:13:0:21a:4aff:fef3:978
Connecting to bpaste.net (bpaste.net)|84.22.98.66|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://bpaste.net/ [following]
--2015-01-24 04:08:57--  https://bpaste.net/
Connecting to bpaste.net (bpaste.net)|84.22.98.66|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: '/dev/null'

     0K .......... .........                                    291M=0s

2015-01-24 04:08:58 (291 MB/s) - '/dev/null' saved [19471]

FINISHED --2015-01-24 04:08:58--
Total wall clock time: 1.8s
Downloaded: 1 files, 19K in 0s (291 MB/s)

**Comment by Antonio-Malcolm** [comment]
I take it that was to share what's installed on my system currently?

**Comment by xtraeme** [comment]
yes

**Comment by Antonio-Malcolm** [comment]
ii ConsoleKit2-0.9.2_3                     A framework for defining and tracking users, login sessions, and seats
ii GConf-3.2.6_6                           A process-transparent configuration system
ii NetworkManager-1.0.0_2                  Network Management daemon
ii accountsservice-0.6.40_1                D-Bus interfaces for querying and manipulating user account information
ii acl-2.2.52_3                            Access Control List filesystem support
ii acpid-2.0.23_8                          The ACPI Daemon (acpid) With Netlink Support
ii adwaita-icon-theme-3.14.1_2             Theme consisting of a set of icons for GTK+
ii alsa-lib-1.0.28_1                       The Advanced Linux Sound Architecture (ALSA) library
ii alsa-plugins-pulseaudio-1.0.28_3        Advanced Linux Sound Architecture (ALSA) extra plugins - Pulseaudio output plugin
ii alsa-utils-1.0.28_3                     The Advanced Linux Sound Architecture (ALSA) utils
ii apg-2.2.3_3                             Automated Password Generator
ii aspell-0.60.6.1_7                       Spell checker with good multi-language support
ii at-spi2-atk-2.14.1_1                    A GTK+ module that bridges ATK to D-Bus at-spi
ii at-spi2-core-2.14.1_1                   Assistive Technology Service Provider Interface
ii atk-2.14.0_1                            Set of interfaces for accessibility
ii attr-2.4.47_4                           Extended attribute support library for ACL support
ii avahi-glib-libs-0.6.31_15               Avahi glib shared libraries
ii avahi-libs-0.6.31_18                    Avahi shared libraries
ii base-directories-0.32_1                 Void Linux base system directories/symlinks
ii base-files-0.114_3                      Void Linux base system files
ii base-system-0.102_1                     Void Linux base system meta package
ii bash-4.3.033_1                          The GNU Bourne Again Shell
ii bluez-5.27_1                            Bluetooth tools and daemons
ii btrfs-progs-20141006.3.18.1_1           Btrfs filesystem utilities
ii bzip2-1.0.6_9                           The bzip2 compression library
ii ca-certificates-20141019_1              Common CA certificates
ii cairo-1.14.0_2                          Vector graphics library with cross-device output support
ii cantarell-fonts-0.0.16_1                Cantarell family of TrueType fonts
ii caribou-0.4.16_1                        An alternative to the Gnome On-screen Keyboard
ii celt-0.11.3_1                           An audio codec for use in low-delay speech and audio communication
ii cinnamon-2.4.6_1                        GNOME3 fork of Linux Mint with GNOME2 aspect
ii cinnamon-control-center-2.4.2_2         The Cinnamon Control Center
ii cinnamon-desktop-2.4.2_1                Library with common API for various Cinnamon modules
ii cinnamon-menus-2.4.1_1                  Cinnamon menu specifications
ii cinnamon-screensaver-2.4.0_1            The Cinnamon screensaver
ii cinnamon-session-2.4.3_1                The Cinnamon session handler
ii cinnamon-settings-daemon-2.4.3_1        The Cinnamon Settings Daemon
ii cinnamon-translations-2.4.2_1           Translations for Cinnamon and Nemo
ii cjs-2.4.1_1                             Javascript for Cinnamon
ii clutter-1.20.0_2                        OpenGL based interactive canvas library
ii clutter-gst-2.0.12_1                    GStreamer bindings for the Clutter Toolkit
ii clutter-gtk-1.6.0_1                     GTK+3 bindings for the Clutter Tolkit
ii cogl-1.18.2_2                           Library for using 3D graphics hardware for rendering
ii colord-gtk-0.1.26_1                     GTK support library for colord
ii coreutils-8.23_4                        The GNU core utilities
ii coreutils-doc-8.23_4                    The GNU core utilities - documentation files
ii cpio-2.11_6                             GNU copy-in/out (cpio) with remote magnetic tape (rmt) support
ii curl-7.40.0_2                           Client that groks URLs
ii dash-0.5.8_1                            POSIX-compliant Unix shell, much smaller than GNU bash
ii dbus-1.8.14_2                           Message bus system
ii dbus-glib-0.102_5                       GLib bindings for D-Bus
ii dbus-libs-1.8.14_2                      Message bus system - shared libraries
ii dbus-x11-1.8.14_2                       Message bus system - X11 support
ii dconf-0.22.0_1                          A low-level configuration system
ii dejavu-fonts-ttf-2.34_2                 DejaVu family of TrueType fonts
ii desktop-file-utils-0.22_4               Utilities to manage desktop entries
ii device-mapper-2.02.115_1                Device Mapper userspace library and tools
ii dhcpcd-6.6.7_1                          RFC2131 compliant DHCP client
ii diffutils-3.3_5                         The GNU diff utilities
ii dnssec-anchors-20141121_2               DNSSEC trust anchors for the root zone
ii dosfstools-3.0.27_1                     DOS filesystem tools
ii dracut-040_4                            A new initramfs infrastructure
ii e2fsprogs-1.42.12_1                     Ext2/3/4 Filesystem Utilities
ii e2fsprogs-libs-1.42.12_1                Ext2/3/4 Filesystem Utilities - shared libraries
ii efibootmgr-0.11.0_2                     Tool to modify UEFI Firmware Boot Manager Variables
ii enchant-1.6.0_1                         Generic spell checking library
ii encodings-1.0.4_5                       X11 Font Index Generator
ii ethtool-3.18_1                          Utility for controlling network drivers and hardware
ii eudev-2.1.1_4                           systemd's udev fork (enhanced userland device daemon)
ii eudev-libgudev-2.1.1_4                  systemd's udev fork (enhanced userland device daemon) - gudev runtime library
ii eudev-libudev-2.1.1_4                   systemd's udev fork (enhanced userland device daemon) - runtime library
ii evolution-data-server-3.12.10_1         Centralized access to appointments and contacts
ii exempi-2.2.2_1                          Library for applications dealing with netlink sockets
ii expat-2.1.0_4                           XML parser library written in C
ii f2fs-tools-1.4.0_1                      Tools for the Linux Flash-Friendly File System (F2FS)
ii faac-1.28_9                             AAC audio encoder library
ii faad2-2.7_7                             AAC decoding library
ii file-5.22_1                             File type identification utility
ii findutils-4.4.2_10                      The GNU Find Utilities
ii firefox-35.0_1                          Lightweight gecko-based web browser
ii font-adobe-100dpi-1.0.3_3               Standard 100dpi Adobe PCF fonts
ii font-adobe-75dpi-1.0.3_3                Standard 75pi Adobe PCF fonts
ii font-adobe-utopia-100dpi-1.0.4_3        100dpi Adobe Utopia PCF fonts
ii font-adobe-utopia-75dpi-1.0.4_3         100dpi Adobe Utopia PCF fonts
ii font-adobe-utopia-type1-1.0.4_3         Adobe Utopia Type1 fonts
ii font-alias-1.0.3_3                      Standard aliases for X11 PCF fonts
ii font-bh-100dpi-1.0.3_3                  Standard 100dpi Bigelow and Holmes PCF fonts
ii font-bh-75dpi-1.0.3_3                   Standard 75dpi Bigelow and Holmes PCF fonts
ii font-bh-lucidatypewriter-100dpi-1.0.3_3 100dpi Bigelow and Holmes Lucida Typewriter PCF fonts
ii font-bh-lucidatypewriter-75dpi-1.0.3_3  75dpi Bigelow and Holmes Lucida Typewriter PCF fonts
ii font-bh-ttf-1.0.3_3                     Standard Bigelow and Holmes TrueType fonts
ii font-bh-type1-1.0.3_3                   Standard Bigelow and Holmes Type1 fonts
ii font-bitstream-100dpi-1.0.3_3           Standard 100dpi Bitstream PCF fonts
ii font-bitstream-75dpi-1.0.3_3            Standard 100dpi Bitstream PCF fonts
ii font-bitstream-type1-1.0.3_3            Standard Type1 Bitstream PCF fonts
ii font-cursor-misc-1.0.3_3                Standard X11 cursors in PCF format
ii font-daewoo-misc-1.0.3_3                Daewoo Gothic PCF format
ii font-dec-misc-1.0.3_3                   DEC cursor and session PCF fonts
ii font-ibm-type1-1.0.3_3                  IBM Courier Type1 fonts
ii font-isas-misc-1.0.3_3                  72dpi PCF versions of the Chinese Song Ti fonts
ii font-jis-misc-1.0.3_3                   78dpi PCF versions of the Japanese fixed fonts
ii font-misc-misc-1.1.2_3                  Standard X11 fixed PCF fonts
ii font-mutt-misc-1.0.3_3                  100dpi PCF versions of the ClearlyU fonts
ii font-util-1.3.0_4                       Tools for truncating and subseting of ISO10646-1 BDF fonts
ii fontconfig-2.11.1_3                     Library for configuring and customizing font access
ii freetype-2.5.5_1                        Font rendering engine and library API
ii fribidi-0.19.6_2                        Free Implementation of the Unicode Bidirectional Algorithm
ii fuse-2.9.3_4                            Filesystem in Userspace
ii gawk-4.1.1_3                            The GNU awk utility
ii gcr-3.14.0_1                            GNOME crypto package
ii gdb-7.8.2_1                             The GNU Debugger
ii gdbm-1.11_4                             GNU database routines
ii gdk-pixbuf-2.31.2_1                     An Image loading library for The GTK+ toolkit (v2)
ii geoclue2-2.1.10_1                       The Geoinformation Service (2.x series)
ii geocode-glib-3.14.0_1                   GLib library for geocoding and reverse geocoding
ii giflib-5.1.1_1                          Library for GIF images
ii gir-freedesktop-1.42.0_1                Introspection data for some FreeDesktop components
ii gjs-1.42.0_2                            Mozilla-based javascript bindings for the GNOME platform
ii glib-2.42.1_1                           The GNU library of C routines
ii glib-networking-2.42.1_1                Network-related giomodules for glib
ii glibc-2.20_9                            The GNU C library
ii glibc-locales-2.20_9                    The GNU C library - locale data files
ii glu-9.0.0_4                             Mesa OpenGL utility library (GLU)
ii glxinfo-8.2.0_4                         Tool to diagnose problems with 3D acceleration setup
ii gmime-2.6.20_2                          GNOME Core mime parsing library
ii gmp-6.0.0_2                             Library for arbitrary precision arithmetic
ii gnome-backgrounds-3.14.1_1              Set of background images for the GNOME Desktop
ii gnome-bluetooth-3.14.0_1                The GNOME Bluetooth Subsystem
ii gnome-control-center-3.14.2_3           The GNOME control center
ii gnome-desktop-3.14.2_1                  GNOME desktop management utilities
ii gnome-icon-theme-3.12.0_1               Theme consisting of a set of icons for GNOME
ii gnome-icon-theme-symbolic-3.12.0_1      GNOME Desktop icon theme (symbolic icons)
ii gnome-keyring-3.14.0_1                  GNOME password and secret manager
ii gnome-online-accounts-3.14.3_1          GNOME service to access online accounts
ii gnome-session-3.14.0_1                  GNOME session management utilities
ii gnome-settings-daemon-3.14.2_1          GNOME settings daemon
ii gnome-shell-3.14.3_1                    GNOME core user interface
ii gnome-themes-standard-3.14.2.3_1        Standard GNOME themes
ii gnupg-1.4.18_1                          The GNU Privacy Guard
ii gnutls-3.3.12_1                         GNU Transport Layer Security library
ii gpgme-1.5.3_1                           GnuPG Made Easy
ii graphite-1.2.4_1                        Reimplementation of the SIL Graphite text processing engine
ii grep-2.21_1                             The GNU grep utility
ii grilo-0.2.11_1                          Framework focused on making media discovery and browsing easy
ii grub-2.00_18                            GRand Unified Bootloader 2
ii grub-x86_64-efi-2.00_18                 GRand Unified Bootloader 2 - x86_64 EFI support
ii gsettings-desktop-schemas-3.14.1_1      Collection of GSettings schemas
ii gst-plugins-bad1-1:1.4.5_1              GStreamer plugins from the bad set (v1.x)
ii gst-plugins-base1-1:1.4.5_2             GStreamer Base Plug-ins (v1.x)
ii gstreamer1-1:1.4.5_1                    Core GStreamer libraries and elements (1.x)
ii gtk+-2.24.25_2                          The GTK+ toolkit (v2)
ii gtk+3-3.14.7_1                          The GTK+ toolkit (v3)
ii gtk-update-icon-cache-2.24.25_2         The GTK+ toolkit (v2) - The GTK+ update icon cache tool
ii gvfs-1.22.3_1                           Userspace virtual filesystem
ii gzip-1.6_5                              GNU compression utility (replacement for compress)
ii hicolor-icon-theme-0.14_1               Standard icon theme called hicolor
ii hwids-20150118_1                        Hardware Identification Databases
ii iana-etc-2.30_4                         Unix /etc/services and /etc/protocols files
ii ibus-1.5.9_2                            Intelligent Input Bus
ii icu-libs-54.1_1                         Robust and full-featured Unicode services - shared libs
ii iproute2-3.18.0_2                       IP Routing Utilities
ii iputils-20121221_6                      IP Configuration Utilities (and ping)
ii ipw2100-firmware-1.3_4                  Firmware for the Intel PRO/Wireless 2100 wifi cards
ii ipw2200-firmware-3.1_4                  Firmware for the Intel PRO/Wireless 2200BG wifi cards
ii iso-codes-3.57_1                        List of country, language and currency names
ii iw-3.17_1                               nl80211 based CLI configuration utility for wireless devices
ii js-1.8.5_7                              Spidermonkey JavaScript interpreter and library
ii json-c-0.12_1                           A JSON implementation in C
ii json-glib-1.0.2_1                       A JSON parser for GLib-based libraries and applications
ii kbd-2.0.2_2                             Linux keyboard utilities
ii kbd-data-2.0.2_2                        Linux keyboard utilities - keymaps, console fonts and unicode maps
ii kmod-19_1                               Linux kernel module handling
ii lcms2-2.6_1                             Small-footprint color management engine, version 2
ii less-471_1                              Pager program similar to more(1)
ii libEGL-10.4.2_1                         Free implementation of the EGL API - runtime
ii libGL-10.4.2_1                          Graphics library similar to SGI's OpenGL
ii libICE-1.0.9_1                          Inter Client Exchange (ICE) library for X
ii libSM-1.2.2_2                           X Session Management Library
ii libX11-1.6.2_3                          Base X libraries from Xorg
ii libXau-1.0.8_1                          Authorization Protocol for X
ii libXaw-1.0.12_2                         X Athena Widgets Library
ii libXcomposite-0.4.4_3                   X Composite Library
ii libXcursor-1.1.14_4                     Client-side cursor loading library for X
ii libXdamage-1.1.4_4                      The Xdamage extension Library
ii libXdmcp-1.1.1_4                        X Display Manager Control Protocol library X.org
ii libXevie-1.0.3_5                        X Event Interceptor Library
ii libXext-1.3.3_1                         X Extension library
ii libXfixes-5.0.1_3                       Xfixes library and extension of X RandR from modular X.org
ii libXfont-1.5.0_1                        X font Library
ii libXft-2.3.2_1                          Library for configuring and customizing font access
ii libXi-1.7.4_1                           X Input extension library
ii libXinerama-1.1.3_2                     X PanoramiX extension library
ii libXmu-1.1.2_2                          X Miscellaneous Utilities library
ii libXpm-3.5.11_2                         X PixMap Library from modular Xorg X11
ii libXrandr-1.4.2_2                       X RandR Library from X.org
ii libXrender-0.9.8_2                      X Render Library
ii libXt-1.1.4_3                           X Toolkit Intrinsics library
ii libXtst-1.2.2_2                         X Tst Library
ii libXv-1.0.10_2                          Xv Extension library
ii libXvMC-1.0.8_2                         XVideo Motion Compensation Library
ii libXxf86misc-1.0.3_1                    Library for the XFree86-Misc X extension
ii libXxf86vm-1.1.3_3                      Library for the XFree86-VidMode X extension
ii libarchive-3.1.2_15                     Library to read/write several different streaming archive formats
ii libass-0.12.1_1                         A portable library for SSA/ASS subtitles rendering
ii libassuan-2.2.0_1                       IPC library used by some GnuPG related software
ii libasyncns-0.8_8                        C library for executing name service queries asynchronously
ii libatasmart-0.19_3                      ATA S.M.A.R.T. Reading and Parsing Library
ii libblkid-2.25.2_4                       Library to handle device identification
ii libbluray-0.6.2_1                       Library to access Blu-Ray disks for video playback
ii libcanberra-0.30_6                      XDG Sound Theme and Name Specification library implementation
ii libcanberra-gtk3-0.30_6                 XDG Sound Theme and Name Specification library implementation - GTK+ (3.x) support
ii libcap-2.24_3                           POSIX.1e capabilities suite
ii libcap-ng-0.7.4_2                       An alternate POSIX capabilities library
ii libcap-progs-2.24_3                     POSIX.1e capabilities suite - utilities
ii libcdparanoia-10.2_10                   CDDA reading utility with extra data verification features - runtime library
ii libcheese-3.14.2_1                      GNOME tool to take pictures and videos from your webcam - shared libraries
ii libcinnamon-control-center-2.4.2_2      The Cinnamon Control Center - runtime library
ii libcolord-1.2.8_1                       System daemon for managing color devices - runtime library
ii libcracklib-2.9.2_1                     Password Checking Library - runtime library
ii libcroco-0.6.8_3                        Toolkit to parse and manipulate CSS (Cascading Style Sheets)
ii libcrypto30-2.1.3_1                     Version of the TLS/crypto stack forked from OpenSSL - crypto library
ii libcups-2.0.1_2                         Common Unix Printing System - client runtime shared libraries
ii libcurl-7.40.0_2                        The multiprotocol file transfer library
ii libdb-5.3.28_2                          The Berkeley DB embedded database system - C shared libraries
ii libdca-0.0.5_8                          DTS Coherent Acoustics decoder
ii libdrm-2.4.59_1                         Userspace interface to kernel DRM services
ii libdvdnav-5.0.1_1                       Library to navigate DVDs
ii libdvdread-5.0.0_1                      DVD access library
ii libedit-20141030.3.1_1                  Port of the NetBSD Command Line Editor Library
ii libefivar-0.15_2                        Library to manipulate EFI variables
ii libelf-0.160_1                          Utilities to handle ELF object files - runtime library
ii libenca-1.16_1                          Extremely Naive Charset Analyser and converter - shared library
ii libepoxy-1.2_1                          Library for handling OpenGL function pointer management for you
ii libevdev-1.3.2_1                        Wrapper library for evdev devices
ii libevent-2.0.22_2                       Abstract asynchronous event notification library
ii libexif-0.6.21_4                        EXIF file library
ii libffi-3.2.1_1                          Library supporting Foreign Function Interfaces
ii libfftw-3.3.4_2                         Library for computing the discrete Fourier transform (DFT) - runtime libraries
ii libflac-1.3.1_1                         Free Lossless Audio Codec - shared libraries
ii libfontenc-1.1.2_2                      The fontenc Library from X.org
ii libgbm-10.4.2_1                         Mesa Generic buffer management API - runtime
ii libgcc-4.9.2_2                          The GNU C Compiler - GCC library
ii libgcrypt-1.6.2_1                       GNU cryptographic library
ii libgdata-0.16.1_1                       Library for accessing GData webservices
ii libgdm-3.14.1_2                         GNOME Display Manager - runtime libraries
ii libgee08-0.16.1_1                       GObject collection library (0.8.x API)
ii libgirepository-1.42.0_1                Library for handling GObject introspection data (runtime library)
ii libglade-2.6.4_11                       Runtime interpreter for GLADE GUI files
ii libglapi-10.4.2_1                       Free implementation of the GL API - shared library
ii libgnome-keyring-3.12.0_1               GNOME keyring client library
ii libgnomekbd-3.6.0_4                     Gnome keyboard configuration library
ii libgpg-error-1.17_1                     Library for error values used by GnuPG component
ii libgsm-1.0.13_12                        GSM 06.10 lossy speech compression
ii libgtop-2.30.0_1                        Library to retrieve system information, used in GNOME
ii libgusb-0.2.4_1                         GLib wrapper around libusb1
ii libgweather-3.14.3_1                    GNOME Weather information access library
ii libharfbuzz-0.9.38_1                    An OpenType text shaping engine - runtime library
ii libhunspell-1.3.3_2                     An Improved spellchecker - runtime library
ii libical-1.0_1                           Reference implementation of the iCalendar data type and format
ii libidn-1.29_1                           Internationalized string handling library
ii libimobiledevice-1.1.7_4                A library to communicate with Apple devices
ii libinput-0.7.0_1                        Library to handle input devices in Wayland compositors and to provide a generic X.Org input driver
ii libjack-1.9.10_5                        JACK Audio Connection Kit low-latency sound server (pro audio) - runtime library
ii libjpeg-turbo-1.4.0_1                   Derivative of libjpeg which uses SIMD instructions
ii libkmod-19_1                            Linux kernel module handling - runtime shared library
ii libldap-2.4.40_3                        OpenLDAP (Lightweight Directory Access Protocol) libraries
ii libldns-1.6.17_3                        Modern DNS/DNSSEC library
ii liblightdm-gobject-1.12.2_1             Light Display Manager - GObject support library
ii libllvm-3.5.1_1                         Low Level Virtual Machine - runtime library
ii libltdl-2.4.2_9                         Runtime libraries for GNU Libtool Dynamic Module Loader
ii liblzma-5.2.0_1                         XZ-format compression library
ii libmagic-5.22_1                         File type identification library
ii libmm-glib-1.4.2_1                      Mobile broadband modem management service - GLib library
ii libmms-0.6.4_1                          MMS stream protocol library
ii libmodplug-0.8.8.5_1                    A MOD playing library
ii libmount-2.25.2_4                       A mount(8) library
ii libmp4v2-2.0.0_3                        MPEG-4 library from mpeg4ip
ii libmpg123-1.21.0_1                      Fast console MPEG audio decoder/player - Runtime library
ii libndp-1.4_1                            Library for Neighbor Discovery Protocol
ii libnemo-2.4.5_1                         The Cinnamon file manager (nautilus fork) - runtime library
ii libnl3-3.2.25_1                         Netlink Protocol Library Suite
ii libnm-1.0.0_2                           Network Management daemon - shared libraries
ii libnm-gtk-1.0.0_1                       NetworkManager panel applet for GNOME - runtime library
ii libnotify-0.7.6_2                       Desktop notification library
ii liboauth-1.0.3_2                        C library implementing OAuth Core RFC 5849
ii libogg-1.3.2_1                          The Ogg bitstream file format library
ii libopenjpeg2-2.1.0_1                    Open-source JPEG 2000 codec written in C language (Version 2) - library files
ii libpciaccess-0.13.2_2                   X11 PCI Access library
ii libpcre-8.36_1                          Perl Compatible Regular Expressions - shared libraries
ii libplist-1.12_3                         Apple Property List library
ii libpng-1.6.16_1                         Library for manipulating PNG images
ii libproxy-0.4.11_1                       A library handling all the details of proxy configuration
ii libpulseaudio-5.0_11                    A featureful, general-purpose sound server - shared libraries
ii libpwquality-1.2.4_1                    Library for password quality checking and generating random passwords
ii libressl-2.1.3_1                        Version of the TLS/crypto stack forked from OpenSSL
ii libressl-openssl-2.1.3_1                Version of the TLS/crypto stack forked from OpenSSL - utilities
ii librsvg-2.40.6_1                        SVG library for GNOME
ii librtmp-2.4_7                           Toolkit for RTMP streams - shared library
ii libsamplerate-0.1.8_3                   Sample Rate Converter for audio
ii libsasl-2.1.26_1                        Cyrus SASL - runtime shared libraries
ii libsecret-0.18_2                        GObject based library for accessing the Secret Service API
ii libsmartcols-2.25.2_4                   Table or Tree library from util-linux
ii libsmbclient-3.6.24_3                   Shared libraries for communication with SMB/CIFS servers
ii libsndfile-1.0.25_4                     C library for reading and writing files containing sampled sound
ii libsoup-2.48.1_1                        HTTP library implementation in C
ii libsoup-gnome-2.48.1_1                  HTTP library implementation in C - GNOME libraries
ii libsrtp-1.4.4_3                         Library implementing SRTP, the Secure Real-time Transport Protocol
ii libssl30-2.1.3_1                        Version of the TLS/crypto stack forked from OpenSSL - SSL/TLS library
ii libstdc++-4.9.2_2                       The GNU C Compiler - Standard C++ Library
ii libtasn1-4.2_1                          ASN.1 structure parser library
ii libtdb-1.3.4_1                          Trivial Database - shared library
ii libtheora-1.1.1_7                       Theora Video Compression Codec
ii libtls1-2.1.3_1                         Version of the TLS/crypto stack forked from OpenSSL - new TLS library
ii libupower-glib1-0.9.23_6                Abstraction for enumerating power devices - runtime library
ii libupower-glib2-0.99.0_4                Abstraction for enumerating power devices - runtime library
ii libusb-1.0.19_2                         A library which allows userspace access to USB devices
ii libusb-compat-0.1.5_4                   A libusb-0.1 compatibility library
ii libusbmuxd-1.0.10_1                     USB Multiplex Daemon library
ii libutempter-1.1.6_3                     Library interface to record user sessions in utmp/wtmp files
ii libuuid-2.25.2_4                        UUID library
ii libvdpau-0.9_1                          The Video Decode and Presentation API for UNIX
ii libvisual-0.4.0_8                       Abstraction library for audio visualisation plugins
ii libvorbis-1.3.4_2                       The Vorbis General Audio Compression Codec
ii libvpx-1.3.0_1                          The VP8 Codec
ii libwacom-0.11_1                         Library to identify wacom tablets
ii libwayland-egl-10.4.2_1                 Free implementation of the EGL API - wayland runtime
ii libwebp-0.4.2_1                         WebP image format
ii libxbps-0.43.1_5                        The XBPS package system utilities - runtime library
ii libxcb-1.11_2                           X protocol C-language Binding
ii libxkbcommon-0.5.0_1                    Library to handle keyboard descriptions
ii libxkbcommon-x11-0.5.0_1                Library to handle keyboard descriptions - X11 support
ii libxkbfile-1.0.8_3                      The xkbfile Library from X.org
ii libxklavier-5.3_4                       Library providing high-level API for X Keyboard Extension
ii libxml2-2.9.2_2                         Library providing XML and HTML support
ii libxshmfence-1.2_1                      X Shared memory 'SyncFence' synchronization primitive
ii libxslt-1.1.28_5                        XSLT parser library from the GNOME project
ii lightdm-1.12.2_1                        Light Display Manager
ii lightdm-gtk3-greeter-1.8.5_1            Light Display Manager GTK+ Greeter (GTK+ 3.x)
ii linux-3.18_1                            The Linux kernel meta package
ii linux-firmware-amd-20150109_1           Binary firmware blobs for the Linux kernel - AMD CPU/GPU microcode
ii linux-firmware-network-20150109_1       Binary firmware blobs for the Linux kernel - network
ii linux3.18-3.18.3_1                      The Linux kernel and modules (3.18 series)
ii lzo-2.08_2                              Portable lossless data compression library
ii man-pages-3.78_1                        Linux Documentation Project (LDP) manual pages
ii mdadm-3.3.2_3                           A tool for managing/monitoring Linux md device arrays
ii mdocml-1.13.2_5                         The mandoc UNIX manpage compiler toolset
ii mesa-intel-dri-10.4.2_1                 Mesa DRI drivers for Intel GPUs
ii mit-krb5-libs-1.12.2_1                  MIT Kerberos 5 implementation - runtime libraries
ii mkfontdir-1.0.7_2                       X11 Font Index Generator
ii mkfontscale-1.1.2_1                     X11 Scalable Font Index Generator
ii mozjs17-17.0.0_2                        Mozilla JavaScript interpreter and library
ii mozjs24-24.2.0_2                        Mozilla JavaScript interpreter and library (24.x series)
ii mtdev-1.1.5_1                           Multitouch Protocol Translation Library
ii muffin-2.4.3_1                          Cinnamon window manager based on Mutter
ii mutter-3.14.3_1                         Lightweight GTK+3 window manager
ii nano-2.3.6_2                            The GNU nano editor
ii ncurses-5.9_9                           A System V Release 4.0 curses emulation library
ii ncurses-base-5.9_9                      A System V Release 4.0 curses emulation library - base terminfo files
ii ncurses-libs-5.9_9                      A System V Release 4.0 curses emulation library -- shared libraries
ii nemo-2.4.5_1                            The Cinnamon file manager (nautilus fork)
ii neon-0.30.1_3                           HTTP and WebDAV client library, with a C interface
ii nettle-2.7.1_3                          A low-level cryptographic library
ii network-manager-applet-1.0.0_1          NetworkManager panel applet for GNOME
ii nspr-4.10.7_1                           NetScape Portable Runtime
ii nss-3.17.3_1                            Mozilla Network Security Services
ii nvi-1.81.6_7                            The Berkeley Vi Editor
ii openbsd-man-20141228_1                  The OpenBSD man(1) utility
ii openssh-6.7p1_8                         The OpenSSH implementation of SSH protocol
ii opus-1.1_2                              Codec designed for interactive speech and audio transmission over the Internet
ii orc-0.4.23_2                            The Oild Runtime Compiler
ii os-prober-1.65_1                        Utility to detect other OSes on a set of drives
ii p11-kit-0.22.1_1                        Provides a way to load and enumerate PKCS#11 modules
ii pam-1.1.8_6                             A flexible mechanism for authenticating users
ii pam-base-0.2_1                          PAM base configuration files
ii pam-libs-1.1.8_6                        A flexible mechanism for authenticating users - runtime libraries
ii pango-1.36.8_1                          Library for layout and rendering of text
ii pciutils-3.3.0_1                        PCI bus related utilities
ii perl-5.20.1_1                           Practical Extraction and Report Language
ii pixman-0.32.6_1                         Library of low-level pixel manipulation routines
ii pm-utils-1.4.1_2                        Power Management Utilities
ii polkit-0.112_5                          Authorization Toolkit
ii polkit-gnome-0.105_6                    PolicyKit integration for the GNOME desktop
ii procps-ng-3.3.10_2                      Utilities for monitoring your system and its processes
ii psmisc-22.21_2                          Small set of utilities that use the linux proc filesystem
ii pulseaudio-5.0_11                       A featureful, general-purpose sound server
ii pygtk-2.24.0_12                         Python bindings for the GTK+ toolkit
ii python-2.7.9_3                          Interpreted, interactive, object-oriented programming language
ii python-Pillow-2.6.2_1                   Python Imaging Library (PIL) fork (Python2)
ii python-atspi-2.12.0_2                   Python2 bindings for AT-SPI
ii python-cairo-1.10.0_5                   Python2 bindings for the cairo graphics library
ii python-dbus-1.2.0_5                     D-Bus Python2 bindings
ii python-gobject-3.14.0_1                 Python2 bindings for GObject
ii python-gobject2-2.28.6_11               Python2 bindings for GObject (GLib 2.x)
ii python-inotify-0.9.4_2                  Monitoring filesystems events with inotify on Linux (Python2)
ii python-lxml-3.4.1_1                     Python2 binding for the libxml2 and libxslt libraries
ii python-pam-0.1.4_5                      Python module for PAM authentication (Python2)
ii python-pexpect-3.3_1                    Python2 module for spawning child applications and controlling them
ii python-setuptools-12.0.4_1              Easily build and distribute Python2 packages
ii python-xdg-0.25_1                       Python2 library to access freedesktop.org standards
ii readline-6.3.008_2                      The GNU Readline Library
ii rest-0.7.92_1                           RESTful library
ii rtkit-0.11_9                            Realtime Policy and Watchdog Daemon
ii run-parts-4.4_1                         Run scripts or programs in a directory
ii runit-2.1.2_3                           A UNIX init scheme with service supervision
ii runit-void-20150117_1                   Void Linux runit scripts
ii sbc-1.3_1                               Bluetooth Subband Codec (SBC) library
ii sed-4.2.2_7                             The GNU stream editor
ii shadow-4.2.1_4                          Shadow password file utilities
ii shared-mime-info-1.3_3                  Core database of common types
ii socklog-2.1.0_1                         Small and secure syslogd replacement for use with runit
ii socklog-void-20141128_1                 Void Linux socklog configuration
ii sound-theme-freedesktop-0.8_1           Freedesktop sound theme
ii soundtouch-1.8.0_1                      SoundTouch Audio Processing Library
ii speexdsp-1.2rc3_1                       A free codec for free speech - DSP
ii sqlite-3.8.8.1_1                        SQL Database Engine in a C Library
ii startup-notification-0.12_9             Library for tracking application startup
ii sudo-1.8.11p2_2                         Allow others to run commands as root
ii talloc-2.1.1_1                          Hierarchical pool based memory allocator with destructors
ii tar-1.28_3                              The GNU tape archiver with remote magnetic tape support
ii telepathy-glib-0.24.1_1                 Library for GLib-based Telepathy components
ii terminator-0.97_2                       tiling terminal emulator application
ii tiff-4.0.3_5                            Library and tools for reading and writing TIFF data files
ii totem-pl-parser-3.10.3_1                Totem playlist parser library
ii traceroute-2.0.21_2                     Traces the route taken by packets over an IPv4/IPv6 network
ii twm-1.0.8_1                             Tab Window Manager for the X Window System
ii tzdata-2014j_1                          Time zone and daylight-saving time data
ii udisks2-2.1.4_1                         Disk Management Service, version 2
ii upower0-0.9.23_6                        Abstraction for enumerating power devices
ii util-linux-2.25.2_4                     Miscellaneous linux utilities
ii void-artwork-20141219_1                 Void Linux artwork
ii vte-0.28.2_8                            Terminal widget with improved accessibility and I18N support
ii vte-python-0.28.2_8                     Terminal widget with improved accessibility and I18N support -- Python bindings
ii wayland-1.6.1_1                         Wayland protocol compositor
ii webkitgtk-2.4.8_2                       GTK+3 port of the WebKit browser engine
ii webrtc-audio-processing-0.1_3           AudioProcessing library based on Google's implementation of WebRTC
ii wget-1.16.1_3                           The GNU wget download utility
ii wgetpaste-2.25_1                        A script that automates pasting to a number of pastebin services
ii which-2.20_3                            Displays where a particular program in your path is located
ii wifi-firmware-1.3_1                     WiFi firmware meta-package
ii wireless_tools-29_6                     Set of tools allowing to manipulate the Wireless Extensions
ii wpa_supplicant-2.3_6                    WPA/WPA2/IEEE 802.1X Supplicant
uu xauth-1.0.9_1                           X authentication utility
ii xbps-0.43.1_5                           The XBPS package system utilities
ii xbps-triggers-0.89_1                    The XBPS triggers for Void Linux
ii xcb-util-0.4.0_1                        XCB utilities library
ii xclock-1.0.7_2                          Analog and digital clock for X
uu xf86-input-evdev-2.9.1_1                Xorg event device input driver
ii xf86-input-synaptics-1.8.1_1            Xorg synaptics touchpad input driver
ii xf86-video-intel-2.99.917_1             Xorg DDX Intel video driver
ii xf86-video-modesetting-0.9.0_2          X.org generic modesetting video driver
ii xfsprogs-3.2.2_1                        Utilities for managing the XFS filesystem
uu xinit-1.3.4_2                           X init program
ii xkbcomp-1.3.0_1                         XKBD keymap compiler
ii xkeyboard-config-2.13_1                 X Keyboard Configuration Database
ii xmlcatmgr-2.2_3                         XML and SGML catalog manager
ii xorg-fonts-7.6_3                        Modular Xorg Fonts
uu xorg-minimal-1.0_2                      Xorg meta-package including xorg-xserver and needed tools
ii xorg-server-1.16.3_1                    The X11 server from X.org
ii xrandr-1.4.3_1                          Primitive command line interface to RandR extension
ii xrdb-1.1.0_2                            X server resource database utility
ii xterm-314_1                             X Terminal Emulator
ii zd1211-firmware-1.5_1                   Firmware for the Zydas 1211 wifi cards
ii zenity-3.14.0_1                         Display GNOME dialogs from the command line
ii zlib-1.2.8_6                            A compression/decompression Library

**Comment by xtraeme** [comment]
You'll have to `strace -f` cinnamon-settings to see which pkg needs the `pam_start` symbol.

**Comment by Antonio-Malcolm** [comment]
Best I can tell, there's a mmap call binding mprotect just before the error:
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff39bb19000

4096 is mprotect.

Other than that, there appear to be a lot of "Illegal Seek" messages.

**Comment by asergi** [comment]
I think I found the culprit: python-pam.
```
[alessio@/home/alessio/void-packages/masterdir /]$ python
Python 2.7.9 (default, Jan  3 2015, 11:00:54) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pam.py", line 76, in <module>
    PAM_START = LIBPAM.pam_start
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: pam_start
>>>
```
It searches for `libpam.so` which is in pam-devel. In fact:
```
[alessio@/home/alessio/void-packages/masterdir /]$ sudo xbps-install -Suy pam-devel
Password: 
[...]
pam-devel-1.1.8_6: installed successfully.

0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
[alessio@/home/alessio/void-packages/masterdir /]$ python 
Python 2.7.9 (default, Jan  3 2015, 11:00:54) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pam
>>>
```
It works! :)

**Comment by Antonio-Malcolm** [comment]
Great, I'll try that, as well.
With two confirming it works, should the cinnamon package be updated to include it as a dependency?

**Comment by xtraeme** [comment]
No, will make another change.

**Comment by xtraeme** [comment]
So does it work if /usr/lib/libpam.so symlink exists?

**Comment by Antonio-Malcolm** [comment]
Neither is working for me.
As best as I can tell, all the dev package, with regard to libpam.so, does if create a symlink to libpam.so.0.83.1

**Comment by xtraeme** [comment]
I've pushed that change... try `xbps-install -Syuv` and see if you can reproduce it again.

**Comment by Antonio-Malcolm** [comment]
Still not seeing it. I'm not sure why- looking over the Python source code, it supposedly looks in ~/lib, /usr/local/lib, and /usr/lib for these libraries.

**Comment by Antonio-Malcolm** [comment]
Also odd, when I run:
$ ldd $(which python) | grep 'libpam'

I get nothing.
Running (with sudo, to catch everything):
 
$ sudo ldd /{,usr/}{bin,sbin}/* | grep -B 5 'libpam' | grep '^/'

Doesn't show Python in the list which can use PAM.

**Comment by xtraeme** [comment]
python is not linked and does not require pam.

python-pam loads the pam shared library dynamically.

**Comment by Antonio-Malcolm** [comment]
Except for me, apparently ;)

**Comment by xtraeme** [comment]
Seriously, not sure what's going on in your system. But I'm not able to reproduce it on any of my 4 machines...

**Comment by Antonio-Malcolm** [comment]
AH, and neither am I, now-
?!
Apparently, installing gcc fixed the issue, for me.
It's something I had come across, hinted at in similar issues mentioned elsewhere, via Google. I had tried it before your most recent pushes, but it didn't work, then.

**Comment by Antonio-Malcolm** [comment]
Oh, yeah, and thanks for working with me on this, guys. Absolutely loving Void, so far!

**Comment by xtraeme** [comment]
Try this:

# xbps-pkgdb -m manual libgcc
# xbps-remove -Ryv gcc

Let me know if that works just with 'libgcc'.


2015-01-24 20:50 GMT+01:00 Antonio-Malcolm <notifications@github.com>:

**Comment by Antonio-Malcolm** [comment]
No, it only works when I install the gcc-c++ package.

**Comment by xtraeme** [comment]
Seriously, I can't belive this.

**Comment by Antonio-Malcolm** [comment]
LMAO. Seriously, I am NOT making this up. I'm not certain WHY it requires something in that package, but it only works with it installed.

**Comment by xtraeme** [comment]
I could reproduce it in a live image with cinnamon.

Seems to be a missing shlib symlink; after running ldconfig python is able to load the pam module.

I'm looking into it to see which symlink it is.

**Comment by Antonio-Malcolm** [comment]
Awesome, thanks!
I will be rolling this same setup, or similar, on a 2011 MacBook Pro and a 2013 MacBook Pro, and, possibly, a Core i7 Shuttle box, so I can provide plenty of testing, if it helps.

**Comment by xtraeme** [comment]
And finally found the reason, python ctypes/util.py contains:

```
        def find_library(name):
            return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
```

That means that python's find_library() relies on an up to date `/etc/ld.so.cache` or if that fails, relies in objdump + gcc.

This explains why this worked for you after installing gcc.

**Comment by xtraeme** [comment]
For the record, this time I'm pretty sure the issue has been fixed because I verified it with a live image.

Just upgrade your system and cinnamon-settings will work correctly.

**Comment by Antonio-Malcolm** [comment]
Yup! Will run the update, thanks!
