### ISSUE TITLE
packages with just a post_install() fail

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#9313]
### System

* xuname:  
  *Void 4.13.14_1 x86_64 GenuineIntel notuptodate rrrdFFF*

* package:  
  *packages with just a post_install() in the template*

### Expected behavior
xbps-src should have changed to ${wrksrc}
### Actual behavior
xbps-src is elsewhere and e.g. `vlicense LICENSE` doesn't work
### Steps to reproduce the behavior
Since the update https://github.com/voidlinux/void-packages/commit/2810b865cb4df2d784170d3b972b9c1ee6c80e1c and previous 2-3 try to build a package with just post_install() like e.g. jsoncpp or snappy.

**Comment by ebfe** [comment]
likely `ch_wrksrc` should be called before calling each function.  jsoncpp fails because `build_style=cmake`s do_install switches directories.

**Comment by pullmoll** [comment]
As I see it moving `common/xbps-src/shutils/common.sh` call of `ch_wrksrc` from `run_step()` to `run_func()` should fix this. I have a commit pending so perhaps someone else can fix this.

**Comment by ebfe** [comment]
Yes, though previously there was no `cd wrksrc` between {pre,do,post}{build,configure}. So let's hope nobody relied on that.

**Comment by pullmoll** [comment]
If this is the case, we'd to fix the packages relying on not being in `${wrksrc}` or `${wrksrc}/${build_wrksrc}` at the start of a template function. At least post_install() obviously had changed to `${wrksrc}` before.

**Comment by ebfe** [comment]
Not sure if moving `ch_wrksrc` to `run_func` works. `run_func` is also used for `do_fetch` which I think is responsible for `create_wrksrc`.

**Comment by pullmoll** [comment]
Oh, in that case perhaps just add it before the `run_func "post_$step_name"` line? Or add a function `ch_wrksrc_if_exists` or similar which doesn't error out if the path not yet exists.

**Comment by Gottox** [comment]
This only occurs with `build_style=cmake` and is caused by the fact that the cmake do_install functions changes the working directory to ./build.

This is exactly the behavior change described in the commit message:

>This causes slightly different behavior to do_install:
>    Do install will chdir to wrksrc only _before_ the first step. The
>    current behavior is that pre_install will run without a chdir, do_ and
>    post_ is runned with a chdir. This is a subtle but breaking change and
>    may cause some templates to break at install phase.

I fixed the behavior in 2d678d4188ccd2cc4a3101fd63582f53df220bfe.

In my opinion it should be possible for the pre_* phase to adjust the working directory for the following do_* phase, but I'm leaving this issue open for further discussions.

**Comment by ebfe** [comment]
It isn't really fixed. See for example gosu which uses `build_wrksrc`.

**Comment by ebfe** [comment]
> In my opinion it should be possible for the pre_* phase to adjust the working directory for the following 
> do_* phase, but I'm leaving this issue open for further discussions.

if you want to the build_styles `do_*` to not run in `wrksrc` you set `build_wrksrc`. If you override `do_*` there is never a reason to even have `pre_*`/`post_*`.

**Comment by ebfe** [comment]
https://build.voidlinux.eu/builders/aarch64-musl_builder/builds/6470/steps/shell_3/logs/stdio

**Comment by Gottox** [comment]
Hmm... true.

I'll switch to run ch_wrksrc right before every phase.

**Comment by pullmoll** [comment]
Solved.

**Comment by ebfe** [comment]
> Solved.

No, just less broken:

```
$ ./xbps-src pkg gosu
[...]
=> gosu-0.12.1_1: running post_install ...
=> ERROR: gosu-0.12.1_1: vinstall: cannot find '../COPYING'...
```

`build_style=cmake` + `build_wrksrc`.

**Comment by Gottox** [comment]
@ebfe I had reworked this based on your comments: Are you okay with it? https://github.com/Gottox/void-packages/tree/ch_wrksrc_each_phase

**Comment by ebfe** [comment]
If it works, yes.
